import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useOthers, useUpdateMyPresence } from '@liveblocks/react'

const Home: NextPage = () => {
  const others = useOthers()
  const otherCursors = others.map((user) => user.presence?.cursor)
  const updateMyPresence = useUpdateMyPresence()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          There {others.count === 1 ? 'is' : 'are'} {others.count}{' '}
          {others.count === 1 ? 'other' : 'others'} with you in the room right
          now.
        </p>

        <div
          style={{ width: '1000px', height: '580px', border: '2px solid gold' }}
          onPointerMove={(e) => {
            updateMyPresence({ cursor: { x: e.clientX, y: e.clientY } })
            console.log(e.clientX, e.clientX)
          }}
        >
          {otherCursors.map(
            (cursor) =>
              cursor && (
                <svg
                  width={50}
                  height={50}
                  viewBox="0 0 50 50"
                  style={{
                    position: 'absolute',
                    left: cursor.x,
                    top: cursor.y,
                    transform: 'translate(-50%, -50%)'
                  }}
                >
                  <circle cx="25" cy="25" r="8" />
                </svg>
              )
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
